# Generated by Django 5.0.2 on 2024-02-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
