# Generated by Django 5.0.2 on 2024-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0008_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
