# Generated by Django 5.0.2 on 2024-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
