# Generated by Django 5.0.2 on 2024-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0016_remove_orders_cart_orders_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
