# Generated by Django 5.0.2 on 2024-03-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0018_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
