# Generated by Django 5.0.2 on 2024-03-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0021_alter_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='furn.cart'),
            preserve_default=False,
        ),
    ]
