# Generated by Django 5.0.2 on 2024-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0022_orders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ManyToManyField(to='furn.cart'),
        ),
    ]
