# Generated by Django 5.0.2 on 2024-03-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0023_remove_orders_cart_orders_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='deliverey_date',
            new_name='delivery_date',
        ),
    ]
