# Generated by Django 5.0.2 on 2024-03-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0024_rename_deliverey_date_orders_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_date',
        ),
    ]
