# Generated by Django 5.0.2 on 2024-03-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0026_remove_orders_cart_orderitem_orders_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furn.address'),
        ),
    ]
